### ISSUE TITLE
Unable to build Project - A problem occurred starting process 'command 'dist-build/android-arm.sh''

### ISSUE THREAD

**Issue by GaaTY** [servalproject/batphone#129]
Hello

I am having a serious struggle building this project.  I am running Windows 10 with Android Studio 2.3.3. I have all the SDK's installed, and the NDK. Android Studio is pointed to their locations.

See screenshot when trying to build in Android Studio.
![build-error](https://user-images.githubusercontent.com/17968700/29362200-3b29752a-828b-11e7-898c-361140d0602c.JPG)

I read somewhere that you don't support building it in Android Studio but only from Command Line. I have installed Bash for Windows, Git, Cygwin. I navigate to the directory and run ./gradlew assembleDebug (as per the instuctions) - I get the same error in the terminal as above.

I don't know what else to do to get it to build. Any help will be appreciated.

**Comment by lakeman** [comment]
I assume a tweak like this will fix it?
https://stackoverflow.com/questions/25562207/execute-shell-script-in-gradle

**Comment by GaaTY** [comment]
Tried as suggested in the link, no change.

Here is the stacktrace:
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'dist-build/android-arm.sh''
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        ... 2 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'dist-build/android-arm.sh'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
        ... 2 more
Caused by: java.io.IOException: **Cannot run program "dist-build/android-arm.sh" (in directory "C:\Users\Bjorn\batphone\app\src\main\jni\libsodium"): CreateProcess error=2, The system cannot find the file specified**
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 5 more
Caused by: java.io.IOException: **CreateProcess error=2, The system cannot find the file specified**
        ... 6 more
Above says it cannot find the file - but the file is definitely there - see screenshot:
![build-error-2](https://user-images.githubusercontent.com/17968700/29365787-71d8c03c-8298-11e7-9141-3c3bf40d8209.JPG)

**Comment by GaaTY** [comment]
So I went ahead and got myself a copy of a Linux OS (Fedora 26). Installed it. Installed Android Studio. Cloned the project and submodules. Downloaded and installed the SDK's and NDK for Linux. Followed the instructions to the letter in INSTALL.md. Now getting this error:

> **Process 'command 'dist-build/android-arm.sh'' finished with non-zero exit value 1**

In Android Studio. In Terminal. I don't know what else to do here. I can't even get this project to build.

**Comment by kbmulligan** [comment]
I was running into the same issues, so here's what I did to make some progress:

> Process 'command 'dist-build/android-arm.sh'' finished with non-zero exit value 1

The above error was coming from the libsodium build script not having a ./configure file available to run. So I had to manually run ./autoconfig.sh in the libsodium directory first. Then this error stopped coming up. This may have been because I didn't do the git submodule init / update.

**Comment by MonicaGPH** [comment]
after cloning project from https://github.com/servalproject/batphone in android studio. I got error 'Error:Execution failed for task ':app:libsodiumBuild'.
> A problem occurred starting process 'command 'dist-build/android-arm.sh'''
 Above suggestion doesn't work for me..

**Comment by quixotique** [comment]
At the moment, we are not actively developing the Batphone app for Android because our funding imposes other priorities.  Jeremy is putting his effort into the new Android app https://github.com/servalproject/serval_chat and I am working on a new iOS app.  The recent changes in on the development branch of https://github.com/servalproject/serval-dna now embed the libsodium source code as a Git subtree (copied) rather than a Git submodule, but we have not updated the Batphone build to take advantage of this.  You are most welcome to tackle this problem.

**Comment by darkcoderrises** [comment]
I went through the same issue. For me, the problem was that git submodule update could not find libsodium tree. So, I ran [this](https://stackoverflow.com/questions/14768509/unable-to-checkout-git-submodule-path), followed by ./autoconfig.sh

**Comment by vibhubpatel** [comment]
My Error is this : Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'ndk-build.cmd'

Please Give Proper Answer...

Thank u !!

**Comment by lakeman** [comment]
No idea, perhaps one of these google results will be informative?

https://www.google.com/search?q=net.rubygrapefruit.platform.NativeException

**Comment by vibhubpatel** [comment]
My Error is this : Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'ndk-build.cmd'

Give Solution for This Question.

**Comment by lakeman** [comment]
If you have a different problem, you should create a new issue. Be sure to add enough information for me to reproduce it. Right now, I have no idea.
