### ISSUE TITLE
 ./gradlew assembleDebug error!

### ISSUE THREAD

**Issue by whitefly20182018** [servalproject/batphone#145]
./gradlew assembleDebug
Unzipping /home/whitefly/.gradle/wrapper/dists/gradle-3.3-all/55gk2rcmfc6p2dg9u9ohc3hw9/gradle-3.3-all.zip to /home/whitefly/.gradle/wrapper/dists/gradle-3.3-all/55gk2rcmfc6p2dg9u9ohc3hw9
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1428)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by lakeman** [comment]
Either a file download problem, or a java 9 bug (https://github.com/junit-team/junit5/issues/881)?
Either way, this issue is nothing to do with our software.
